[theme]
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"

[server]
maxUploadSize = 50
enableCORS = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false